Improve error handling in frontend and backend (#123)
* Install winston@3.3.3 package

* Create winston logger

* Call getUser & createUser inside try block

* Simplify error response for signup controller

By attaching message and error code.

* logger err in signup controller & createUser, getUsers services

* Add `logs` directory in gitignore

* Emit click event in LText component

* Set error.message to empty string for custom error message

* Update "Already have an account? Log in" in Join.vue

* Handle hideError() in LText component

Instead of writing hideError message for individual component.

Hide the error messaage in LText component.

* Show inline-error for user_exists in join.vue

* Set "Required" error.message for empty input value

* Add buttonLoading if condition in join.vue

* Show inline-error in login.vue

Show inline error message below input field for
* USER_NOT_FOUND
* INCORRECT_PASSWORD

* Update "Don't have an account yet? Sign up" in login.vue

* Access login for blocked users

Instead of completely blocking the access for blocked users.

Their access will be limited on the features a user have access to.

* logger err in controller, middlewares and services

* Move await function inside try-catch block

NOTE: This commit changes across multiple files.

* fix: logger utility require path

* fix: change `user` variable name in createUser service

Duplication of variable names inside try-catch block.

Error: `user` const variable before Initialising

* fix: invalidToken error message response

* Remove "welcome onboard"  & "welcome back" alert from join and login page

* Update postBySlug 404 error message & code

* Show "There is no such post." for POST_NOT_FOUND

* Convert userById controller to async function

* Convert updateUser controller to async function

* Create tokenErrorHandle mixin

* Use userNotFound error method via tokenErrorHandle mixin

* Check if userId exists in created hook

Instead of checking if userId exists in getUser method.

Check inside created lifecycle hook.

* Show "There is no such post." in post edit page

* Replace "authorizeUser" with "validateUserAccess"

validateUserAccess function also check for authUser to be an owner or moderator.

* Pass user data to next middleware

Before passing data next middleware remove password from user object.

* Convert updatePost controller to async function

* Redirect back for edit post with "NOT_ENOUGH_PERMISSION" error

* Use tokenErrorHandle error in CreatePost and Vote component

* Update error code "BOARD_NOT_FOUND" & add logger

* log create board error in try-catch block

Remove the if-else condition and directly send the response back.

* Remove response 500 for "post_not_created"

* Add "INVALID_TOKEN" error code to logger in token middleware

* Align input error message to right

* Add "invalidAuthHeaderFormat" error handler to CreatePost and Votes component

* Add logger to migrations files

* Log frontend error messages with console.error()